name: Delivery
on:
  push:
    branches:
      - master

jobs:
  commit:
    name: Commit
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          path: argocd-playground

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Test
        working-directory: argocd-playground
        run: |
          make test

      - name: Update version.json
        working-directory: argocd-playground
        run: |
          make update-commit
        env:
          COMMIT: ${GITHUB_SHA}

      - name: Build docker image
        working-directory: argocd-playground
        run: |
          make build-docker
        env:
          TAG: ${GITHUB_SHA}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: hpcsc
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Push to Github Container Registry
        working-directory: argocd-playground
        run: |
          make push-docker
        env:
          TAG: ${GITHUB_SHA}

  staging-manifest:
    name: Update staging manifest
    needs: commit
    runs-on: ubuntu-20.04
    steps:
      - name: Check out manifest repo
        uses: actions/checkout@v2
        with:
          repository: hpcsc/argocd-playground-manifest
          path: argocd-playground-manifest
          token: ${{ secrets.MANIFEST_REPO_TOKEN }}

      - uses: imranismail/setup-kustomize@v1
        with:
          github-token: ${{ secrets.MANIFEST_REPO_TOKEN }}

      - name: Update image tag
        working-directory: argocd-playground-manifest
        run: |
          make set-image-tag
        env:
          TAG: ${GITHUB_SHA}

      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: argocd-playground-ci
          author_email: argocd-playground-ci@example.com
          cwd: argocd-playground-manifest
          message: Update image tag to ${{ github.sha }}
          pull: NO-PULL
          push: true

  deploy-staging:
    name: Deploy to staging
    needs: staging-manifest
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v2
        if: ${{ env.ACT == 'true' }}
        with:
          path: argocd-playground

      - name: Setup argocd CLI
        uses: clowdhaus/argo-cd-action/@main
        if: ${{ env.ACT == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 2.1.2
          command: version
          options: --client

      - name: Sync ArgoCD staging application
        working-directory: argocd-playground
        if: ${{ env.ACT == 'true' }}
        run: |
          make sync-staging
        env:
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
          ARGOCD_SERVER_URL: ${{ secrets.ARGOCD_SERVER_URL }}

      - name: Run smoke test
        working-directory: argocd-playground
        if: ${{ env.ACT == 'true' }}
        run: |
          make smoke-test
        env:
          SERVER_URL: ${{ secrets.STAGING_SERVER_URL }}
          TAG: ${GITHUB_SHA}
