name: Delivery
on:
  push:
    branches:
      - master

jobs:
  commit:
    name: Commit
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          path: argocd-playground

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Test
        working-directory: argocd-playground
        run: |
          make test

      - name: Update version.json
        working-directory: argocd-playground
        run: |
          make update-commit
        env:
          COMMIT: ${GITHUB_SHA}

      - name: Build docker image
        working-directory: argocd-playground
        run: |
          make build-docker
        env:
          TAG: ${GITHUB_SHA}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: hpcsc
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Push to Github Container Registry
        working-directory: argocd-playground
        run: |
          make push-docker
        env:
          TAG: ${GITHUB_SHA}

  staging-manifest:
    name: Staging
    uses: hpcsc/argocd-playground/.github/workflows/manifest-job.yaml@master
    needs: commit
    with:
      tag: ${GITHUB_SHA}
    secrets:
      manifest_repo_token: ${{ secrets.MANIFEST_REPO_TOKEN }}

  deploy-staging:
    name: Staging
    uses: hpcsc/argocd-playground/.github/workflows/deploy-job.yaml@master
    needs: staging-manifest
    with:
      tag: ${GITHUB_SHA}
      argocd_app_name: argocd-playground-app-staging
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      argocd_token: ${{ secrets.ARGOCD_TOKEN }}
      server_url: ${{ secrets.ARGOCD_SERVER_URL }}
      argocd_server_url: ${{ secrets.STAGING_SERVER_URL }}
