name: CI
on:
  push:
    branches:
      - master

jobs:
  commit:
    name: Commit
    runs-on: ubuntu-20.04
    steps:
    - name: Check out
      uses: actions/checkout@v1

    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Test
      run: |
        make test

    - name: Build docker image
      run: |
        make build-docker
      env:
        TAG: ${GITHUB_SHA}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: hpcsc
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: true

    - name: Push to Github Container Registry
      run: |
        make push-docker
      env:
        TAG: ${GITHUB_SHA}
