name: Deploy job using ArgoCD

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      argocd_app_name:
        required: true
        type: string
    secrets:
      github_token:
        required: true
      argocd_token:
        required: true
      server_url:
        required: true
      argocd_server_url:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v2
        if: ${{ env.ACT == 'true' }}
        with:
          path: argocd-playground

      - name: Setup argocd CLI
        uses: clowdhaus/argo-cd-action/@main
        if: ${{ env.ACT == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          version: 2.1.2
          command: version
          options: --client

      - name: Sync ArgoCD staging application
        working-directory: argocd-playground
        if: ${{ env.ACT == 'true' }}
        run: |
          make sync-staging
        env:
          ARGOCD_TOKEN: ${{ secrets.argocd_token }}
          ARGOCD_SERVER_URL: ${{ secrets.argocd_server_url }}
          ARGOCD_APP_NAME: ${{ inputs.argocd_app_name }}

      - name: Run smoke test
        working-directory: argocd-playground
        if: ${{ env.ACT == 'true' }}
        run: |
          make smoke-test
        env:
          SERVER_URL: ${{ secrets.server_url }}
          TAG: ${{ inputs.tag }}
