name: Update Manifest Job

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      manifest_repo_token:
        required: true

jobs:
  update-manifest:
    name: Update manifest
    runs-on: ubuntu-20.04
    steps:
      - name: Check out manifest repo
        uses: actions/checkout@v2
        with:
          repository: hpcsc/argocd-playground-manifest
          path: argocd-playground-manifest
          token: ${{ secrets.manifest_repo_token }}

      - uses: imranismail/setup-kustomize@v1
        with:
          github-token: ${{ secrets.manifest_repo_token }}

      - name: Update image tag
        working-directory: argocd-playground-manifest
        run: |
          make set-image-tag
        env:
          TAG: ${{ inputs.tag }}

      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: argocd-playground-ci
          author_email: argocd-playground-ci@example.com
          cwd: argocd-playground-manifest
          message: Update image tag to ${{ github.sha }}
          pull: NO-PULL
          push: true
